name: Docker image publish

on:
  push:
    tags:
    - '*'

jobs:
  docker-image-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: publish
        uses: pennsignals/publish_docker-compose@v0.1.0
        with:
          version: '0.2.6-rc.1'
          docker_compose: 'docker-compose.yml'
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
