name: Docker Compose Publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: publish
      uses: pennsignals/publish_docker-compose@v0.1.0
      with:
        docker_compose: 'src/docker-compose.yml' # required
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
