name: .NET build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  dotnet-build:
    runs-on: ubuntu-latest
    env:
      working-directory: src

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      working-directory: ${{env.working-directory}}
      run: dotnet restore
      
    - name: Build
      working-directory: ${{env.working-directory}}
      run: dotnet build --no-restore