name: .NET Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  dotnet-build:
    runs-on: ubuntu-latest
    env:
      working-directory: src

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      working-directory: ${{env.working-directory}}
      run: dotnet restore QuickLink.sln
      
    - name: Build
      working-directory: ${{env.working-directory}}
      run: dotnet build --no-restore QuickLink.sln
